config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions do
    member do
      get :make_recurring
    end
  end

  resources :plans

  post 'paypal/ipn_listener' => 'paypal#ipn_listener'

  root 'plans#index'
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates :paypal_description, length: { maximum: 120 }

  def paypal_description=(value)
    write_attribute(:paypal_description, I18n.transliterate(value))
  end

  def to_s
    name
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessor :paypal_payment_token

  belongs_to :plan

  delegate :price, :paypal_description, to: :plan

  def cancel!
    update(cancel: true)
  end

  def paid?
    return false if paid_until.blank?
    paid_until >= Time.current
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paypal_controller.rb
class PaypalController < ApplicationController
  protect_from_forgery except: [:ipn_listener]

  def ipn_listener
    if params[:txn_type].present?
      PaypalSubscription::NotificationHandler.resolve!(
        subscription: subscription,
        notification: notification
      )
    end

    render nothing: true
  end

  private

  def subscription
    @subscription ||=
      Subscription.find_by!(
        id: notification.reference,
        paypal_payer_id: notification.payer_id
      )
  end

  def notification
    @notification ||= PayPal::Recurring::Notification.new(params)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = Subscription.all
  end

  def show
  end

  def create
    @subscription = Subscription.create(subscription_params)
    redirect_to checkout_url
  end

  def make_recurring
    if PaypalSubscription::RecurrenceCreator.create!(
        subscription: subscription,
        paypal_options: paypal_options.merge({
          payer_id: params[:PayerID],
          token: params[:token]
        })
      )
      redirect_to subscription_path(subscription),
        notice: I18n.t('flashes.subscription.successfully_created')
    end
  end

  def destroy
    PaypalSubscription::ResourceFacade.cancel(paypal_options)

    redirect_to subscription_path(subscription),
      notice: I18n.t('flashes.subscription.cancellation_asked')
  end

  private

  def checkout_url
    PaypalSubscription::ResourceFacade.checkout_url(
      paypal_options.merge({
        return_url: make_recurring_subscription_url(subscription),
        cancel_url: subscription_url(subscription, aborting_operation: true)
      })
    )
  end

  def paypal_options
    @paypal_options ||=
      PaypalSubscription::DefaultOptions.for(subscription)
  end

  def subscription
    @subscription ||= Subscription.find(params[:id])
  end
  helper_method :subscription

  def subscription_params
    params.permit(:plan_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaypalSubscriptions</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plans/index.html.erb
<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= number_to_currency(plan.price) %></td>
        <td><%= plan.description %></td>
        <td><%= link_to 'Subscribe', subscriptions_path(plan_id: plan.id),
                                     method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @plan.price %>
</p>

<p>
  <strong>Paypal description:</strong>
  <%= @plan.paypal_description %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plan.description %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/subscriptions/index.html.erb
<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Paid until</th>
      <th>Plan</th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td>
          <%= l(subscription.paid_until, format: :long) if subscription.paid? %>
        </td>
        <td><%= subscription.plan %></td>
        <td><%= link_to 'View', subscription %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paypal payer:</strong>
  <%= subscription.paypal_payer_id %>
</p>

<p>
  <strong>Paypal profile:</strong>
  <%= subscription.paypal_profile_id %>
</p>

<% if subscription.paid? %>
  <p>
    <strong>Paid until:</strong>
    <%= l subscription.paid_until, format: :long %>
  </p>
<% end %>

<p>
  <strong>Plan:</strong>
  <%= subscription.plan %>
</p>

<% if subscription.paid? %>
  <%= link_to 'Cancel',
               subscription_path(subscription),
               method: :delete,
               data: { confirm: 'Are you sure that you want cancel your subscription?' } %> |
<% end %>
<%= link_to 'Back', subscriptions_path %>